### ISSUE TITLE
Implement keybord interaction

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/angular-star-rating#10]
Implement following interactions:
- [x] implement focuse interaction
- [x] increment rating on key up
- [x] decrement rating on key down
- [x] set rating to pressen number

**Comment by BioPhoton** [comment]
Note: To enable focus events on non inputs like div's we can use the ```tabindex``` attribute.

Set the ```tabindex ```to:
- **0** allows the element to receive mouse-clicks and keyboard events (tab key) to  assign focus
- **-1** allows the element to receive mouse-clicks only to assign focus

```html
<div tabindex="0">
click or tab to focus
</div>

<div tabindex="-1">
click to focus
</div>
```

**Comment by eagor** [comment]
when in `readOnly` mode, it would make sense to remove it from from tabbing order?
