### ISSUE TITLE
Support for Angular v9

### ISSUE THREAD

**Issue by vinayakpatil** [BioPhoton/angular-star-rating#114]
Error: Uncaught (in promise): Error: `Importing StarRatingModule which does not have a ɵmod property`

Hi @BioPhoton , is this library deprecated? I don't see any development since years.

**Comment by casper5822** [comment]
Same question, does it support angular 9 ? Thanks

**Comment by billyjov** [comment]
@vinayakpatil @casper5822 A newer Version was published
