### ISSUE TITLE
compound selectors may no longer be extended. SCSS needs update!!!!

### ISSUE THREAD

**Issue by rmoubayed** [BioPhoton/angular-star-rating#115]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

getting the error in the title cause of @extend .className.className you need to modify it and make it into @extend .className, .className

## Environment

<pre><code>
Library version: X.Y.Z
Angular version: X.Y.Z

Browser:

- [ ] Chrome (desktop) version XX
</code></pre>

**Comment by rmolodyko-softheme** [comment]
Try to use: 
`@import '~css-star-rating/css/star-rating.min.css';`
insted of
`@import '~css-star-rating/scss/star-rating';`

**Comment by billyjov** [comment]
Fixed in the latest version
