### ISSUE TITLE
Fix problem with eslint

### ISSUE THREAD

**Issue by benni-h** [BioPhoton/angular-star-rating#116]
### Subject of the feature

eslint is a little unhappy with the current code after updating to angular 12+ and switching from tslint to eslint.

### Problem

Linting our project this output was found blocking the pipeline.

```
node_modules/angular-star-rating/src/angular-star-rating.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

3     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~

node_modules/angular-star-rating/src/angular-star-rating.module.d.ts:4:24 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forChild(): ModuleWithProviders;

```

### Expected behaviour

Eslint should not have a problem without turning off a linting rule for all files.

_(Yes, I could apply a patch to that file automagically in the pipeline. But carrying the fixes from project to project is not fun.)_

##### Local (temporary) fix
Adapting `angular-star-rating.module.d.ts` to

```
import { ModuleWithProviders } from '@angular/core';
export declare class StarRatingModule {
    static forRoot(): ModuleWithProviders<StarRatingModule>;
    static forChild(): ModuleWithProviders<StarRatingModule>;
}
```

helped the linter on my machine.

##### Possible change on the code in the repo???
I **guess** a fix could be applied here?

In `https://github.com/BioPhoton/angular-star-rating/blob/master/libs/angular-star-rating/src/angular-star-rating.module.ts`

1. Line: `static forRoot(): ModuleWithProviders {`
   * Change: `static forRoot(): ModuleWithProviders<StarRatingModule> {`

2. Line: `static forChild(): ModuleWithProviders {`
   * Change: `static forChild(): ModuleWithProviders<StarRatingModule> {`

**Comment by billyjov** [comment]
@benni-h a newer version is available.
