### ISSUE TITLE
Angular Stuck on Compiling

### ISSUE THREAD

**Issue by HadiHt** [BioPhoton/angular-star-rating#121]
I'm using Angular version 13.0.0, with the latest version of star-rating.

I'm using the exact same code written in the installing tab on this repo,
but the compilation is getting stuck on `Generating browser application bundle` when I try to compile,
removing `@import '~css-star-rating/scss/star-rating';` stopped this problem.

I'm also running this on a new project just for testing.
Is this due to version compatibilities?
Any ideas would be appreciated.

**Comment by billyjov** [comment]
@HadiHt Thanks for reporting this.

The issue is related to the newer version of sass. 

This line inside CSS star rating repo causing the issue. 
https://github.com/BioPhoton/css-star-rating/blob/master/src/scss/_modifiers.scss#L163
Any Idea for refactoring this would be helpfull

**Comment by dckhead3000** [comment]
[This](https://github.com/BioPhoton/angular-star-rating/issues/115#issuecomment-655500894) answer worked for me!

**Comment by billyjov** [comment]
@dckhead3000 @HadiHt You can check out the newer version `5.1.0` that contains the fix for this.
