### ISSUE TITLE
console.log made it into production

### ISSUE THREAD

**Issue by AlexanderTang** [BioPhoton/angular-star-rating#122]
### Subject of the issue

Since at least version 5.0.1 (and perhaps earlier) I encounter a bunch of console logs from this dependency.  I updated to the currently latest version 5.1.0 and this console.log has not been removed yet.  It stems from line 259 in angular-star-rating.mjs:

console.log('useHoverValue: ', useHoverValue);

This should be removed.

### Your environment

*   **OS**: Windows 10
*   **Packages**: 
     * "angular-star-rating": "5.1.0"
     *  "css-star-rating": "1.3.1"
*   **Env**: npm 8.1.0

### Steps to reproduce

Simply open a page where the star rating is used.

### Expected behaviour

No console logs visible

### Actual behaviour

Yes console logs visible

**Comment by billyjov** [comment]
Hi @AlexanderTang ..I will deploy a new version were all logs are removed. Thanks for pointing this out

**Comment by billyjov** [comment]
This commit https://github.com/BioPhoton/angular-star-rating/commit/3428421602d1b8089e114504709dd215c3c2fbab
fix this behavior and will come with the next version

**Comment by AlexanderTang** [comment]
Thanks for the quick response and fix!  Cheers.
