### ISSUE TITLE
Cannot find the star-rating.scss at the path ~angular-star-rating/assets/scss/star-rating

### ISSUE THREAD

**Issue by aditbharadwaj** [BioPhoton/angular-star-rating#123]
### Subject of the issue
Cannot find the star-rating.scss at the path ~angular-star-rating/assets/scss/star-rating
Describe your issue here.
Cannot find the star-rating.scss at the path ~angular-star-rating/assets/scss/star-rating when trying to import it using 
@import "~angular-star-rating/assets/scss/star-rating";

Please find below the screenshot of the package in the node modules >> 
![image](https://user-images.githubusercontent.com/6751554/174469737-8e28ccd6-8c61-4122-9113-edf02a3c53c1.png)

This is *not* a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/unified/remark)

### Your environment

*   **OS**: windows
*   **Packages**: 5.1.0
*   **Env**: node v14.16.0 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

What should happen?
The SCSS file should be included in the package 
### Actual behaviour

What happens instead?

**Comment by billyjov** [comment]
Hi..You should use this instead😉: 

`@import '~css-star-rating/scss/star-rating';`

**Comment by aditbharadwaj** [comment]
Thanks 👍 , docs says the other wise soo got confused.
