### ISSUE TITLE
Unable to use Library with Angular v.11

### ISSUE THREAD

**Issue by marcore86** [BioPhoton/angular-star-rating#124]
**Describe the bug**

I am trying to use this library on my project witch has Angular v.11 installed. 
When I build I get errors like:

_Error: ./node_modules/angular-star-rating/fesm2015/angular-star-rating.mjs 1148:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)_

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-v11-isufob?file=src/app/app.module.ts

**Screenshots**

![image](https://user-images.githubusercontent.com/10436263/183706730-d5260872-37db-4b1d-b1ac-1983294bce7f.png)

**Versions**

- `@angular/core`: ~11.2.14
- `rxjs`: ~6.6.0
- `angular-star-rating`: ^6.0.0
- `css-star-rating`:v^1.3.1

Browser name and version:
- [ ] Chrome (desktop)

**Comment by billyjov** [comment]
`angular-star-rating` `v6.0.0` requires Angular 14. Try version 5.1.0 instead.

**Comment by billyjov** [comment]
You can check out this example. https://stackblitz.com/edit/angular-ivy-8gkvhh

With Angular 13 and v 5.0.1

**Comment by marcore86** [comment]
Hi @billyjov ,
thank you for your time but unfortunately I am using Angular V.11 and event with library version 5.0.1 is not working.

Cheers,
