### ISSUE TITLE
No value accessor for form control with name

### ISSUE THREAD

**Issue by damient** [BioPhoton/angular-star-rating#125]
**Describe the bug**
When I use input formControlName="level", I have this error when display the field :
No value accessor for form control with name

**Minimal reproduction of the problem with instructions**
```
    <star-rating starType="svg"
                 size="large"
                 formControlName="level"
                 [numOfStars]="5"
                 [hoverEnabled]="true"></star-rating>
```

**Versions**

- `@angular/core`: 14.1.3
- `rxjs`:  7.5.6
- `angular-star-rating`: 6.0.0
- `css-star-rating`: 1.3.1

Browser name and version:

- [ ] Chrome (desktop) version 104

**Comment by billyjov** [comment]
Hi @damient  i checked your issue and cannot reproduce this on stackblitz. Would you be able to provide a reproduction step using stackblitz? 

https://stackblitz.com/edit/angular-ivy-q89sv9
