### ISSUE TITLE
Star component is not rendered 

### ISSUE THREAD

**Issue by param-bnb** [BioPhoton/angular-star-rating#16]
But i have svg files inside images folder. I have done as per instructions.. What would the bug? i see component is there in source file only it is not rendering

**Comment by BioPhoton** [comment]
Could you provide code snippets or so?

thx!

**Comment by BioPhoton** [comment]
Hi @param-bnb. 

Hope you could solve your problem. I will close this issue now.
Please feel free to reopen it if there is a need to.
