### ISSUE TITLE
Remove console.log in ngOnInit

### ISSUE THREAD

**Issue by rubyboy** [BioPhoton/angular-star-rating#18]
https://github.com/BioPhoton/angular-star-rating/blob/master/src/star-rating.component.ts#L316

![image](https://cloud.githubusercontent.com/assets/1908166/25553929/3f8c8ed0-2cc9-11e7-8ec1-5c4c072f74f3.png)

**Comment by BioPhoton** [comment]
Hi @rubyboy! Thx for your Tine and Interesst in this lib. I will remove it. Asap.

Best Michael

**Comment by BioPhoton** [comment]
fixed in version 2.0.3

**Comment by rubyboy** [comment]
@BioPhoton thanks for much for the prompt response and for the awesome lib.

**Comment by BioPhoton** [comment]
Welcome!
