### ISSUE TITLE
Update library bundling

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/angular-star-rating#19]
- [x] remove inlined templates
- [x] remove inlined styles
- [x] update bundling

For bundling I use yeoman with [this](https://github.com/jvandemo/generator-angular2-library/blob/master/README.md) Generator.

It will also fix #25, #29 and bring some structure for #14.

**Comment by jlkeiper** [comment]
What are the specifics for updating the bundling? I am dealing with #25 and would love to contribute.

**Comment by BioPhoton** [comment]
Hi @jlkeiper ,
I updated the tooling. Please check if you still have the es5 error.

Best Michael
