### ISSUE TITLE
Not rendering

### ISSUE THREAD

**Issue by sguddati** [BioPhoton/angular-star-rating#21]
Hello

I started using the component and I can see the html is rendering. But the rating stars are not visible. Tried playing with different styles and with no luck. Can you please help? I am attaching html that is generated for below html segment. 

<star-rating-comp [rating]="2" [labelText]="activity.reviewCount" [labelPosition]="'right'"></star-rating-comp>
						
Srinivas
[output.txt](https://github.com/BioPhoton/angular-star-rating/files/966351/output.txt)

**Comment by sguddati** [comment]
Any response please

**Comment by BioPhoton** [comment]
Hi @sguddati!

Thx for you issue. 
I guess you think this is a chat :-). My responses willl take some time.

You could try to follow the installing guild in the readme and if if works change it to this.

I can see that you output only the <i> tags. try to add [starType]="svg". This coud help.
In the mean time i will try to create a default version of this lib that don't require any asset...

Best,
Michael

**Comment by xerotolerant** [comment]
hey, the readme.md file has 
`[startype]="'svg'"]` rather than `[starType]="'svg'"` It was not working for me without the uppercase 'T'

**Comment by BioPhoton** [comment]
Hi @xerotolerant,

Nice catch! I will try to fix this in the next week. 

Best,
Michael

**Comment by BioPhoton** [comment]
Hi @xerotolerant! I updated it. It will be in the next release. :-)
