### ISSUE TITLE
AOT compile with Angular CLI fails

### ISSUE THREAD

**Issue by JustinSchneider** [BioPhoton/angular-star-rating#22]
I added angular-star-rating (2.0.1) to my project last week and had no problems running JIT or AOT. Today, my build sever is failing and pointing to the following lines in angular-star-rating:

> /node_modules/angular-star-rating/src/star-rating.component.ts.StarRatingComponent.html (9,17): Supplied parameters do not match any signature of call target.
> /node_modules/angular-star-rating/src/star-rating.component.ts.StarRatingComponent.html (9,17): Supplied parameters do not match any signature of call target.`

I'm looking at the changes over the last few days and don't see anything related to any of the event methods that this error message type usually refers to. Anyone on the team have an idea what this could be about?

**Comment by BioPhoton** [comment]
Hy!

Atw I have no clue why...  Will have a look later this week.

**Comment by JustinSchneider** [comment]
Hey, @BioPhoton. Any luck with finding a cause of this?

**Comment by BioPhoton** [comment]
Hi!

Sry, currently no time... For me it looks like a typing Problem. Did you run lint? What does linting say?

**Comment by eyalhakim** [comment]
I'm running into the same problem, would love to know if any of you finds the solution.
My lint doesn't show any errors btw.

**Comment by BioPhoton** [comment]
Do you Guys use the ts Files or the Compiler js Files?

**Comment by JustinSchneider** [comment]
@BioPhoton I'm not sure how to answer that. It's an angular-cli project (using webpack, but indirectly). Locally I run 'ng serve' (JIT), while our build server does AOT, and that's where the problem shows up. I can replicate this by running our 'ng build -prod' command locally, but beyond that I can't really say.

Still learning a lot of this stuff, unfortunately.

**Comment by BioPhoton** [comment]
Hi! Very fast reply!!!  😎

So how do you Import the lib? 

Please Show me the Line of Code... The Import Statement or so...

THX!

**Comment by JustinSchneider** [comment]
In app.module.ts:
`import { StarRatingModule } from 'angular-star-rating';
@NgModule({
  declarations: [
    ...
  ],
  imports: [
    StarRatingModule
  ]
})`

And then in my component:
`<star-rating-comp 
  [starType]="'svg'" 
  [numOfStars]="10"
  [size]="'large'">
</star-rating-comp>`

Is that what you needed?

**Comment by BioPhoton** [comment]
Yes! Just want to make shure that u use the ts Files.. have to try something. Im back home in 3h I guess....

Just for interest, could you try to Reference the ts Files directly? I guess it's angular-star-rating/src/...module

**Comment by eyalhakim** [comment]
@BioPhoton tried it now, same result :/

**Comment by BioPhoton** [comment]
Thx for trying. Have to look this up! 

Best,
Michael

**Comment by eyalhakim** [comment]
No problem!

Would really appreciate it if you could get to it soon.
It would be a great deal of help!

Thank you

**Comment by mhjmaas** [comment]
It seems you need to modify line 52 in the angular-star-rating sourcecode:

> star-rating.component.ts

 from:

`(mouseleave)="onStarHover()">` to `(mouseleave)="onStarHover($event)">`

AOT compilation needs to match these parameters exactly to be able to do efficient tree shaking I believe. At least when I edit this line, everything starts working fine again. :)

**Comment by BioPhoton** [comment]
Hi @mhjmaas !
BIG THX for your help!

Enjoy AOT in version 3.0.0 on npm

:-)

**Comment by eyalhakim** [comment]
Thank you both!
