### ISSUE TITLE
tslint issue

### ISSUE THREAD

**Issue by morningdew830** [BioPhoton/angular-star-rating#23]
when I run command `npm run lint`, it throws much issues. please see the screenshot following: https://monosnap.com/file/5C4CQ0DrmnVpCC0PIEe4hQ1QYdSyS6

**Comment by BioPhoton** [comment]
Hi @morningdew830. You run the linting in the example folder, not in the src folder.
I do not release the examples in the npm package. Consider it as a nice to have thing which does not go conform with the released package code quality.

Feel free to open this issue again. :-)
