### ISSUE TITLE
It doesn't work in IE11

### ISSUE THREAD

**Issue by pdtoloza** [BioPhoton/angular-star-rating#25]
I think the reason is that the tsconfig has been configured to generate ES6 code.

**Comment by ScottBouloutian** [comment]
I couldn't use this package since it does not target ES5 :(

**Comment by BioPhoton** [comment]
What exactly is the issue? I tested it quickly and for me it worked...

**Comment by pdtoloza** [comment]
the problem is that the transpiled code has ES6 reserved words, like "class", which are not supported in IE11 ([https://kangax.github.io/compat-table/es6/#ie11](https://kangax.github.io/compat-table/es6/#ie11))

**Comment by ScottBouloutian** [comment]
Essentially the same issue on my end, except it was failing for me in PhantomJS, which I am using to run my tests.

**Comment by jac1013** [comment]
Hey guys, any workaround for this at the moment?

**Comment by BioPhoton** [comment]
Why don't you use the ts files and do the compiling yourself. Just include the ts files in a file and your build task will bundle it with the rest of the app.

**Comment by jac1013** [comment]
That is the _not lazy solution_, yes, that's what I'll do, thanks!

**Comment by BioPhoton** [comment]
Hi @jac1013! 
Fyi it's on the Roadmap 😉. Currently just no time. Sry!

If you could you do me a favour and create a PR for #19 I would merge it. 😋

**Comment by BioPhoton** [comment]
Hi @jac1013! 

Any updates from your side about the PR?

**Comment by jac1013** [comment]
Hey @BioPhoton, I plan to work on this later (probably this weekend), what do we exactly need here? changing all the TS files in the distribution to be compiled in ES5? Just double checking that we are in the same page.

**Comment by BioPhoton** [comment]
Wow! Sounds great!

I guess if we just upgrade the build tooling. See #19. Everything should be Fine with the next Version.

Thx
Michael!!!

**Comment by BioPhoton** [comment]
Hi all!

I updated the tooling => #19 

Could you pleases check if the es5/6 error is still present?

Best
Michael
