### ISSUE TITLE
TS files included in published NPM package

### ISSUE THREAD

**Issue by JustinSchneider** [BioPhoton/angular-star-rating#29]
This is news to me, but apparently [NPM packages aren't supposed to contain .ts files](https://github.com/angular/angular-cli/issues/4350#issuecomment-277573957). Having them included is causing my 'ng lint' to scrub those files and yell at me for all the whitespace and doublequote issues.

**Comment by BioPhoton** [comment]
Hi @JustinSchneider!

I will try to:
- [x] fix linting errors,
- [x] exclude ts from npm

If you want to work in the meantime you could exclude node_modules from linting.

"lint": [
  {
    "project": "src/tsconfig.app.json",
    "exclude": "**/node_modules/**/*"
  },
  {
    "project": "src/tsconfig.spec.json",
    "exclude": "**/node_modules/**/*"
  },
  {
    "project": "e2e/tsconfig.e2e.json",
    "exclude": "**/node_modules/**/*"
  }
]

Best Michael

**Comment by BioPhoton** [comment]
Will close this because of finishing #19
