### ISSUE TITLE
Add to npm?

### ISSUE THREAD

**Issue by retallicka** [BioPhoton/angular-star-rating#3]
Hi, great work! 😄 

I looked for an angular2 star rating system exactly like this and I only found your 1.5 version. Any chance of adding this to npm or is it still not ready?

**Comment by BioPhoton** [comment]
Hi @retallicka!

I'm not really done with the bundling and release process.
I could release an beta version were i ship just the ts files. They are quite ready...
Would this be ok for you?


You could also test the bundled version im my example folder. If it works i can do a real release...
PR is welcome!

**Comment by retallicka** [comment]
OK I will try using it and PR if I can

**Comment by BioPhoton** [comment]
added to npm under beta
package name and version: angular-star-rating@2.0.0-beta.0
