### ISSUE TITLE
Add new feature : margin

### ISSUE THREAD

**Issue by jamilalisgandarov** [BioPhoton/angular-star-rating#30]
I leave this issue as advice, I think it would be great if there was a chance to add margin between stars, not flex spacing.

**Comment by BioPhoton** [comment]
Hi @jamilalisgandarov 
You could do this over css i guess? 
Maybe it is also a feature for [css-star-rating](https://github.com/BioPhoton/css-star-rating) which angular-star-rating extends from.

Please let me know if this was helpful.

**Comment by BioPhoton** [comment]
Feel free to open the bug if you need more help.

Best Michael

**Comment by jamilalisgandarov** [comment]
Everything is fine , I just thought it would be easier to use with option, most of the libraries use accepts this kind of option. Thanks for your attention.

**Comment by BioPhoton** [comment]
How would you see this in this lib? Could you give an example?

best
Michael
