### ISSUE TITLE
Two-Way-Binding does not work

### ISSUE THREAD

**Issue by acuntex** [BioPhoton/angular-star-rating#31]
It seems that although you can change the stars, there is no working two-way-binding functionality in this library.

The following code does not work as a two-way-binding:
`          <star-rating-comp class="own-rating" [starType]="'svg'" [(rating)]="profileData.userRating"></star-rating-comp>`

I also tried
`          <star-rating-comp class="own-rating" [starType]="'svg'" [(ngModel)]="profileData.userRating"></star-rating-comp>`

but there seems to be a bug in `star-rating.ts`: Angular passes null in the beginning and the following line tries to call "toString()" on null.
`        this.ratingAsInteger = parseInt(this._rating.toString());
`
There is no check, if the value is actually a number.

Am I doing something wrong or is this actually a bug?

**Comment by BioPhoton** [comment]
Hi @acuntex! Thx for your issue.

Did you look in the documentation at the event bindings?
`<star-rating-comp (onRatingChange)="ctrl.onRatingChange($event)"></star-rating-comp>`

I know if the eventbinding name would be ratingChange it would work as you expect. 
but as the eventObject has a more complex structure, not only the rating value as number but an object with {rating: value}, it may confuse other people. 

just use the (onRatingChange) and consider the $event obj to have following structure {rating: this.rating}.

Was this helpful?

**Comment by BioPhoton** [comment]
Please close it if you could solve your problem.

**Comment by acuntex** [comment]
Yes, my current workaround is `(onRatingChange)="onRatingChange($event)"` and `profileData.userRating = $event.rating;`

**BUT:**
This does not seem to be the Angular way because Angular is a MVVM Framework where you should not need events for such simple assignments.
Because of this there are two-way-bindings. (Same with ngChange - I worked on big projects where there isn't a single one)

**Comment by BioPhoton** [comment]
Hi @acuntex quick answer! :-)

There is no 2-way-binding in angular2+. 
There are property bindings (top down) and event bindings (bottom up). 
`[(ngModel)]="profileData.userRating"`
The banana in a box syntax =>` [(ngModel)]="property"` is just a short hand for the separate version 
`[ngModel]="property" (ngModel)="property = $event"`

in this project it would look like:
`[rating]="property" (onRatingChange)="property = $event.rating"`
and if i would change the naming form onRatingChange to ratingChange
`[rating]="property" (ratingChange)="property = $event.rating"`

The only thing that would be needed to satisfy you is to change the `$event` structure from `{rating: ratingValue}` to `ratingValue`

I want to keep this as it allowes me to easily extend the $event obj without creating a breaking change. 
I could add other data too i.e. time of click or so. 

If you want i could add another event binding additional to `onRatingChange` with name `ratingChange` and it returns just the primitive value. 

At the moment you have to live with `(onRatingChange)="profileData.userRating = $event.rating"`.

Best 
Michael
