### ISSUE TITLE
Production build (Lazy Loading/UglifyJs) with Ionic fails

### ISSUE THREAD

**Issue by acuntex** [BioPhoton/angular-star-rating#32]
When running a production build (Lazy Loading/UglifyJs) with ionic the build fails:
```
Error: ./~/angular-star-rating/index.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/xxx/xxx/node_modules/@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
...
```

Seems like ionic expects (according to https://github.com/ionic-team/ionic-app-scripts/blob/master/src/webpack/optimization-loader-impl.ts) the js files to be besides the ts files.
So I copied the index.js and index.js.map into node_modules/angular-star-rating/ and all *.js and *.js.map files from dist to the src folder.

After that, lazy loading seems to work, but uglifyjs (included in ionic-cli) fails because the js files seem to be ES6 according to the tsconfig.json and uglifyjs supports only ES5 as target.
`Error: Unexpected token: punc ()) in /Users/xxx/xxx/www/build/0.main.js at line 19193, col 36, pos 749043
`

The only workaround at the moment is to include the src-files directly in the project and to build them with the project.

**Comment by BioPhoton** [comment]
Hi @acuntex i updated the tooling. Please check if the bug is still present.

**Comment by BioPhoton** [comment]
Fixed in latest version. Hope i could help.
