### ISSUE TITLE
npm run build prod error unexpected token name

### ISSUE THREAD

**Issue by nobitahuang** [BioPhoton/angular-star-rating#33]
![image](https://user-images.githubusercontent.com/22837417/27805030-5671ac40-605c-11e7-8c02-a1e2bb9e9957.png)

**Comment by BioPhoton** [comment]
Hi @chendzng ,
there is a new version out. please check if the bug still exist.

Best Michael

**Comment by thib92** [comment]
@BioPhoton works fine with latest update, thanks a lot 😄

**Comment by BioPhoton** [comment]
NICE! So i close this one...
