### ISSUE TITLE
Error with UglifyJsPlugin with Webpack

### ISSUE THREAD

**Issue by thib92** [BioPhoton/angular-star-rating#34]
I just installed this module, and when trying to compile it with Webpack (using UglifyJsPlugin plugin with minimize option), I get the following error :
`ERROR in app.bundle.js from UglifyJs
Unexpected token: name (StarRatingConfig) [app.bundle.js:47135,4]`

When removing UglifyJsPlugin from my Webpack plugins list, everything compiles just fine.

I am disabling UglifyJsPlugin for now but I'd need it to work !

Thanks 👍

**Comment by BioPhoton** [comment]
Hi @thib92, Thanks for your issue!

This is actually a duple of #33 so i close it because of redundancy.
