### ISSUE TITLE
Hover not working

### ISSUE THREAD

**Issue by alex88** [BioPhoton/angular-star-rating#38]
I've included the library and my html is
```
<star-rating-comp [starType]="'icon'" [hoverEnabled]="true"></star-rating-comp>
```
when hovering I see the `hover-{1,2,3...}` class however I see only empty stars

Maybe the component isn't supposed to do that?

**Comment by MohsenAra** [comment]
i have same issue

**Comment by alex88** [comment]
@MohsenAra I think the library isn't supposed to do that, you should use `onHoverRatingChange` to get a temporary value, set it to the component and when the `$event` you receive from `onHoverRatingChange` is null, restore the old value

**Comment by MohsenAra** [comment]
Thanks man
that is ok , like this 

`
        this.starRatingConfig.onHoverRatingChange = ($event: IStarRatingIOnHoverRatingChangeEvent) => {
            if ($event.hoverRating) {
                if (!this.tmpRate)
                    this.tmpRate = this.content.rate;
                this.rate = $event.hoverRating;
            } else {
                this.rate = this.tmpRate;
                this.tmpRate = undefined;
            }

        };`
