### ISSUE TITLE
How to select half star on hover or click?

### ISSUE THREAD

**Issue by lakhvir1994** [BioPhoton/angular-star-rating#39]
How to implement functionality of selecting half star on hover or click.

**Comment by karol-depka** [comment]
Is it possible for the user to select a half-star?
That would help me a lot.
Thank you.
EDIT: I mean for the user to *directly* select e.g. 3.5 rating via mouse/tapping using this component.

**Comment by BioPhoton** [comment]
Hi. No it is only possible over keybord as you know already. THX again for you PR!!

I dont think this is good UX as the star size could change and the user could miss click it. I alos will port this to inoic3 and implement drag. Touch and drag a halfstar is not really nice... At least in my view.

**Comment by BioPhoton** [comment]
Maybe i will implement it in the future. but at the moment a don't have time... 
And if i have time i would start with tests and refactoring instead of new features.

**Comment by BioPhoton** [comment]
@karol-depka 
If you could provide a concept for this feature it may help. I will try to start refactoring soon and then looking at this feature. 
Best Michael
