### ISSUE TITLE
Does not show half rating and how to select half rating on click function?

### ISSUE THREAD

**Issue by 02harleen** [BioPhoton/angular-star-rating#40]
Hi, I have used this plugin but does not show half rating. And the second issue is how to select half rating on click function.
`<star-rating-comp [starType]="'icon'" [rating]=2.6 [readOnly]="true" [showHalfStars]='true'>
  </star-rating-comp>`

**Comment by BioPhoton** [comment]
1. i guess you should use ["] around the rating property.
2. Half stars on click is not supported for now.

Feel free to reopen this issue if needed

Best Michael

**Comment by ericel** [comment]
Is there any plan to support the half-rating event?
