### ISSUE TITLE
I would like to play around with the css

### ISSUE THREAD

**Issue by broosted** [BioPhoton/angular-star-rating#45]
like below 

<star-rating-comp [labelPosition]="'left'" [labelText]="'Rating:'" [starType]="'svg'" [rating]="3"></star-rating-comp>

I would like instead of center the content to override the default 
justify-content: left

and also the above label is not showing did I not place the proper css files in angular cli project ?

**Comment by BioPhoton** [comment]
Hi @broosted 

In the latest version the scss in separate from the component. Have fun!
