### ISSUE TITLE
labelText not working

### ISSUE THREAD

**Issue by sergey-morenets** [BioPhoton/angular-star-rating#47]
Hi

I'm using Angular Star rating version 3.0.3. Browser Chrome.

<star-rating-comp [starType]="'svg'" [rating]="test.rating" [numOfStars]="5" [showHalfStars]="true"
                                [direction]="'ltr'" [labelText]="'1'"></star-rating-comp>
When a page is opened I see five stars and four stars are filled. But there is no text displayed(the one I specified in [labelText].

Please advice.

**Comment by MrHOY** [comment]
@sergey-morenets 
You can try add [labelVisible]="true"

in README, I see [labelVisible] with Default value: true, but I think it not work.

**Comment by BioPhoton** [comment]
Hi @sergey-morenets yes use [labelVisible]. but in the latest version i rolled back this feature.
