### ISSUE TITLE
css-star-rating not in dependecies

### ISSUE THREAD

**Issue by asimhashmi** [BioPhoton/angular-star-rating#49]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

ng serve gives error, because it is not able to find star-rating.scss in the path
```css
@import "~css-star-rating/dist/scss/star-rating.scss";
```
it depends on css-star-rating which is not mentioned anywhere in the documentation,
you should add css-star-rating to dependencies,

## Expected behavior

ng serve runs successfully as it finds all the required files

## Minimal reproduction of the problem with instructions
1 - install angular-star-rating 3.0.4(latest) according to the documentation
2- start ng serve

## Environment

<pre><code>
Library version: 3.0.4
Angular version: 4.3.1

**Comment by BioPhoton** [comment]
Hi @asimhashmi thanks for the issue!

I added it to the dependencies. Give it a try!
