### ISSUE TITLE
'star-rating-comp' is not a known element:

### ISSUE THREAD

**Issue by ThakkarKhushbu** [BioPhoton/angular-star-rating#50]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

'star-rating-comp' is not a known element:

## Expected behavior

I follow all instruction , but when i am trying to use       <star-rating-comp></star-rating-comp> it gives me an error ``
## Environment
**@angular/cli: 1.2.7
node: 6.10.2
os: win32 x64
 @angular/animations : 4.3.4
 @angular/cdk : 2.0.0-beta.8
 @angular/common : 4.3.4
 @angular/compiler : 4.3.4
 @angular/core : 4.3.4
 @angular/forms:  #4.3.4
 @angular/http : 4.3.4
 @angular/material : 2.0.0-beta.8
 @angular/platform-browser: 4.3.4
 @angular/platform-browser-dynamic: 4.3.4
 @angular/router : 4.3.4
 @angular/cli : 1.2.7
 @angular/compiler-cli : 4.3.4**

<pre><code>
Library version: X.Y.Z
Angular version: X.Y.Z

Browser:

- [ ] Chrome (desktop) version XX
</code></pre>

**Comment by BioPhoton** [comment]
I can not reproduce it... Can you take a look at the example [here](https://github.com/BioPhoton/angular-star-rating/tree/master/examples/angular4). I guess it will help

**Comment by BioPhoton** [comment]
I will Close this one. Feel Free to reopen it.

**Comment by ibuchan72390** [comment]
I ran into this issue when I had multiple lazy-loaded modules from my main app.module.  I had attempted to use the StarRatingModule.forRoot() in my main app.module file; however, that was raising the above error for me.  In order for me to get this to work, I had to import the full StarRatingModule into my SharedModule imports collection without the forRoot() method.
