### ISSUE TITLE
Half star not working

### ISSUE THREAD

**Issue by hristijan5** [BioPhoton/angular-star-rating#51]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

Half star is not shown

## Expected behavior

Show half star

## Minimal reproduction of the problem with instructions

class="rating-container"
							[rating]="3.5"
							[starType]="'icon'"
							[size]="'large'"
							[showHalfStars]="true"
							[disabled]="true"
						>

.rating-container {
    float: left;
    cursor: pointer;
}

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 4.2.5

Browser:

- [ x] Chrome (desktop) version 60.0.3112.113
</code></pre>

**Comment by hristijan5** [comment]
So my guess is that half star only works with svg. Should I remove this issue? Thank you!

**Comment by BioPhoton** [comment]
Hi @hristijan5 thanks for the update!!

Yes half stars works only for svg or iconfonts.

To enable half stars for default icon too i have to update the css-star-rating lib for cutting the icon div with overflow hidden.

I will try to update the docs this weekend.

If you want to help me you could take a look at this issue: https://github.com/BioPhoton/css-star-rating/issues/29

**Comment by BioPhoton** [comment]
Hi @hristijan5 
I updated the readme and setup wiki pages.
I also mentioned that half stars are only available in combination with starType svg.

https://github.com/BioPhoton/angular-star-rating/wiki/Property-Bindings#control-modifier

If there is a need feel free to reopen the issue

Best Michael

**Comment by hristijan5** [comment]
Thank you  @BioPhoton. If I can find some free time I may help you with the CSS. cheers!
