### ISSUE TITLE
custom color

### ISSUE THREAD

**Issue by maku** [BioPhoton/angular-star-rating#52]
hi, 

maybe a dump question... But how can I define my own color? 
From the documentation I see only the "predefined" ones working...

**Comment by BioPhoton** [comment]
In version 3.0.8 you have to include the [star.rating.scss](https://github.com/BioPhoton/angular-star-rating/blob/master/src/assets/scss/star-rating.scss) file. 
You could also include the styles from the css only lib here: [star-rating.scss](https://github.com/BioPhoton/css-star-rating/blob/master/src/scss/star-rating.scss)

In this file there are a lot of default variables.
Import that file and override variables as you would with i.e. bootstrap variables.

Was that helpful?

Best Michael

**Comment by maku** [comment]
@BioPhoton I tried it but without success.

I put the following in styles.scss (of my angular-cli project):
```
@import "~angular-star-rating/assets/scss/star-rating";

$color-default-rating: #784699 !default;

```
This had no effect...

**Comment by maku** [comment]
I works when I overwrite the css directly

e.g. for "ok"
```
.rating.color-ok .star-container .star svg {
  fill: #df6c19;
}
```

**Comment by BioPhoton** [comment]
FYI you just made it in the wrong order.

```css
/*Override Colors*/
$color-negative-rating: #0f0 !default;
$color-ok-rating: #f00 !default;
$color-positive-rating: #00f !default;
$color-default-rating: #ff0 !default;

/* You can add global styles to this file, and also import other style files */
@import "~angular-star-rating/assets/scss/star-rating";

```

**Comment by BioPhoton** [comment]
I created more detailed and organized docs.

You could also take a look at this: [Customizing-Styles]( https://github.com/BioPhoton/angular-star-rating/wiki/Customizing-Styles)

**Comment by maku** [comment]
@BioPhoton Great, thank you

**Comment by mani-rai** [comment]
Hello,

I am copying and pasting exactly same style and in same order from wiki page in styles.scss file for testing. But I am seeing no difference. Styles are not getting overriden. I am using 3.0.8 and angular 5+ at the moment. Do you have any idea what could go wrong here?

**Comment by BioPhoton** [comment]
The wiki is for the latest version.
Will move docs back to versioning
