### ISSUE TITLE
Not work with bootstrap 3.3.7

### ISSUE THREAD

**Issue by MrHOY** [BioPhoton/angular-star-rating#53]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
</code></pre>

Before with boostrap 3.3.7, everything ok
![screenshot from 2017-09-07 11-46-29](https://user-images.githubusercontent.com/20653706/30146453-69bbdd36-93c2-11e7-8282-b153d9038947.png)

After upgrade to angular-star-rating 3.0.8
![screenshot from 2017-09-07 11-49-21](https://user-images.githubusercontent.com/20653706/30146506-a20049c0-93c2-11e7-9531-e08d03c93ac4.png)

I use system.config.js not Webpack

## Environment

<pre><code>
Library version: X.Y.Z
Angular version: 4.4.0-RC.0

Browser:

- [ ] Chrome (desktop) version XX
</code></pre>

**Comment by BioPhoton** [comment]
Hi @MrHOY !

Could you solve your issues? Maybe you forgot to include the scss file.

**Comment by MrHOY** [comment]
@BioPhoton 
Yes, have to insert to index.html:
 `<link rel="stylesheet" type="text/css" href="node_modules/css-star-rating/dist/css/star-rating.min.css">`
