### ISSUE TITLE
View error on ratings with a rating more than 5

### ISSUE THREAD

**Issue by maku** [BioPhoton/angular-star-rating#54]
e.g. the following shows only 5 of 10 stars

```
<star-rating-comp starType="svg" [rating]="9" [numOfStars]="10"></star-rating-comp>
````

(any value greater than 5 leads to a view of 5 of 10 stars)

when I provide a fromControl with the the value set (in this case 9) the output is correct.

(Tried to create an example with https://stackblitz.com to show the error but was not able to get it running)

**Comment by BioPhoton** [comment]
You can edit the scss vars. 
Take a look at this line: https://github.com/BioPhoton/css-star-rating/blob/master/src/scss/_variables.scss#L8
