### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by FOSSKolkata** [BioPhoton/angular-star-rating#55]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

Following error is thrown when running the web application on IE 11. Application is running fine on Chrome.

Error: Syntax error
  Evaluating http://localhost:62362/node_modules/angular-star-rating/dist/index.js
  Evaluating http://localhost:62362/app/feeds-app/feeds-app.module.js
  Evaluating http://localhost:62362/app/app.module.js
  Evaluating http://localhost:62362/app/main.js
  Loading my-app/main

## Minimal reproduction of the problem with instructions

Use the component on a web page and run it on IE 11

## Environment
Windows 8.1 64 Bit

<pre><code>
Library version: 3.0.0
Angular version: 4.0.0

Browser:

- [ ] IE 11 Version: 11.0.9600.17031
</code></pre>

**Comment by shekharramola** [comment]
Is this component work with bootstrap-4?

**Comment by manandkumaar** [comment]
I am also facing this issue.  
Is there any work around for this issue?.

IE 11
Windows 7

**Comment by frankmacd1** [comment]
IE 11
Win 7
The stars aren't even appearing.   same page viewed in Chrome Version 66.0.3359.181 (Official Build) (64-bit) is working as expected.. no issues

I had someone view the page using Edge on a Win10 box..  stars appeared, but you to had triple click to get a rating to take.

No errors appear in console in IE.

**Comment by tania686** [comment]
IE 11
Win 10

the same issue exists. are there any updates on the resolution?

**Comment by tania686** [comment]
IE 11
Win 10

@BioPhoton are there any updates on that issue?
The issue still exists.
Even your demo page isn't displayed on IE11.

Please advise.
Thanks

**Comment by antonsamper** [comment]
There's a few options to get it working in IE11:
1. Use starType icons `<star-rating starType="icon">`
2. Use a polyfill to fix the svg reference https://github.com/jonathantneal/svg4everybody

The issue is that IE11 doesnt support the `<use>` tag inside SVGs with an external ref.
```
<svg viewBox="0 0 100 100">
   <use xlink:href="myvector.svg#icon-1"></use>
</svg>
```

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

**Comment by BioPhoton** [comment]
Close as obsolete :)
