### ISSUE TITLE
Set custom ASSETS folder name in config

### ISSUE THREAD

**Issue by WuglyakBolgoink** [BioPhoton/angular-star-rating#57]
Hi,

is it possible to change this hard coded path : `.../assets/images/***.svg` ?

In my project all files placed in `.../images/**` folder. :) and plugin can not find svg file

**Comment by karllhughes** [comment]
It seems like this _would_ be possible except that the `StarRatingConfig` class doesn't get injected through the `forRoot()` method as you would expect: https://github.com/BioPhoton/angular-star-rating/issues/43

So for now, there's no way to change the images directory cleanly, but you could use the `icon` option and then create some css classes with your own background images as a workaround.

**Comment by BioPhoton** [comment]
This is now possible in the latest version. 
See docs [here](https://github.com/BioPhoton/angular-star-rating/wiki/Custom-configuration)
