### ISSUE TITLE
HTML template in Label property

### ISSUE THREAD

**Issue by WuglyakBolgoink** [BioPhoton/angular-star-rating#58]
## I'm submitting a...

```bash
[x] Feature request
```

Is it possible to add a html tags in labels?

<img width="469" alt="bildschirmfoto 2017-10-03 um 20 15 44" src="https://user-images.githubusercontent.com/2271337/31141517-f1b685b4-a877-11e7-887a-0a78eb2f6183.png">

**Comment by BioPhoton** [comment]
Hi @WuglyakBolgoink,
At the moment not. If you really need html in the label section wrap the star rating in your own component and receive value changes over the event binding.

Hope it helps. 

best,
Michael
