### ISSUE TITLE
Disable arrow key input that changes star ratings

### ISSUE THREAD

**Issue by mayoljonathan** [BioPhoton/angular-star-rating#59]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

1. Click the star with readOnly="true" or disabled="true"
2. Pressing arrow keys, and it changes the star ratings.

## Expected behavior

1. Click the star with readOnly="true" or disabled="true"
1. Disable the changing of star ratings using the arrow keys.

## Environment

<pre><code>
Ionic version: 3.6.0
Angular version: 4.1.3

Browser:

- [x] Chrome (desktop) version 61.0.3163.100
</code></pre>

**Comment by BioPhoton** [comment]
@tsebvaan THX for your time and the issue!!

Will try to get some time soon! 

PR's also ok ;-)

**Comment by BioPhoton** [comment]
Is fixed in the latest version.
