### ISSUE TITLE
Custom size beyond small, medium, and large options

### ISSUE THREAD

**Issue by kblestarge** [BioPhoton/angular-star-rating#62]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x] Question
</code></pre>

I want to use a slightly bigger version than the `medium` size but slightly smaller than the `large` size. Is there an easy way to do this? Or should I fork?

**Comment by BioPhoton** [comment]
Easy, just override the css.

Best Michael
