### ISSUE TITLE
Update package deps for angular 5.x

### ISSUE THREAD

**Issue by j-walker23** [BioPhoton/angular-star-rating#67]
## I'm submitting a...
<pre><code>
[ ] Bug report  
[x ] Feature request
</code></pre>

Please upgrade to angular 5.x if possible.
Yarn installs give warnings like `angular-star-rating@3.0.8" has incorrect peer dependency "@angular/core@^4.0.0".`

**Comment by j-walker23** [comment]
I guess i should ask first. Would this lib have any issues with angular 5?
If not, then this can be closed.
I didn't use angular 4 so i don't know the differences.

**Comment by solkaz** [comment]
Used this package on Angular 4 and 5, there were no problems when we upgraded. So this _should_ be safe.

**Comment by j-walker23** [comment]
Awesome, thank you @solkaz.

**Comment by rbleuse** [comment]
Yes it works, but we can't shrinkwrap dependencies because of this error :

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: @angular/core@^4.0.0, required by angular-star-rating@3.0.8
npm ERR! peer invalid: @angular/forms@^4.0.0, required by angular-star-rating@3.0.8
```
