### ISSUE TITLE
Star component not being rendered on chrome

### ISSUE THREAD

**Issue by aqarabsa** [BioPhoton/angular-star-rating#70]
## Current behavior
SVG images for the stars are not being rendered on chrome 63

## Expected behavior
SVG images should be rendered 

## Minimal reproduction of the problem with instructions
1- install angular-star-rating with version 3.0.8

2- import StarRatingModule into your module
<pre><code>
@NgModule({
    imports: [
    StarRatingModule.forRoot(),
    ]
</code></pre>

3- use star-rating-comp in html template

 <star-rating-comp 
            [starType]="'svg'" 
            [numOfStars]="5"
            [hoverEnabled]="true" 
            [size]="'medium'"
            [rating]="5"
            (onClick)="onRatingChange($event)">
</star-rating-comp>

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 5.0.0

Browser:

-  Chrome (desktop) version 63
</code></pre>

**Comment by alexpetrus20** [comment]
I have the same issue. The stars did not appear, ut the style is loaded. Did you find a solution?

**Comment by BioPhoton** [comment]
I guess you didn't copy the image into your assets folder? Try  check this.

**Comment by alexpetrus20** [comment]
I checked again and the svg image is there, no error but nothing is displayed.

**Comment by BioPhoton** [comment]
Hi you can check the [live demo](https://biophoton.github.io/angular-star-rating). Maybe you can spot what you are missing.
