### ISSUE TITLE
Prefix css class name

### ISSUE THREAD

**Issue by brackio** [BioPhoton/angular-star-rating#71]
## I'm submitting a...

[ X] Bug report  

Can you prefix your classes.  Some of your css classes have general names (for example: "rating"), and it is causing css conflicts with my app css classes.

## Current behavior

CSS class are not prefix.

## Expected behavior

Add prefix to CSS classes to avoid conflicts.  For example, instead of class-name "rating", it should be renamed to "asr-rating".

**Comment by BioPhoton** [comment]
Hi @brackio !
Thx for your feedback. 
As the lib uses 'css-star-rating' for styling the issue belongs to this lib. 

Could you be so kind and reopen it there?
