### ISSUE TITLE
[showHalfStars] doesn't work

### ISSUE THREAD

**Issue by ghost** [BioPhoton/angular-star-rating#8]
I used: 
<star-rating-comp  [rating]=h.rate [showHalfStars]='true' [readOnly]='true' [size]="'medium'"></star-rating-comp>

but my half-stars are still the full-ones... any suggestions?

**Comment by savchukm** [comment]
+1

**Comment by BioPhoton** [comment]
hi @savchukm  and @ghost!

Everything should be working in the latest release. 

Please check it and give me feedback or reopen this issue it the error is still occurs.
