### ISSUE TITLE
This package does not come with the assets folder

### ISSUE THREAD

**Issue by rodrigoyoshida** [BioPhoton/angular-star-rating#81]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

Following the install instructions, it tells me to copy the images from assets folder inside the angular-star-rating from node_modules, but after installing through npm I was not able to find any assets folder inside there.

## Expected behavior

Change the instructions or provide the assets folder.

**Comment by BioPhoton** [comment]
THX!! fixed
