### ISSUE TITLE
Half star shown in incorrect way in RTL

### ISSUE THREAD

**Issue by jagshettiwars** [BioPhoton/angular-star-rating#82]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
</code></pre>

## Environment

<pre><code>
Library version: X.Y.Z
Angular version: X.Y.Z

Browser:

- [ ] Chrome (desktop) version XX
</code></pre>

**Comment by BioPhoton** [comment]
Hi! Thx for this issue and your time!! :-)
Check out the [demo](https://biophoton.github.io/angular-star-rating/#/property-bindings) 
It works. What do you exactly mean? 

Feel free to reopen if needed
