### ISSUE TITLE
Unable to get rating value / documentation out of date

### ISSUE THREAD

**Issue by CybrZr00** [BioPhoton/angular-star-rating#84]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

Hi I could do with some guidance please.
I used a previous version of the a while ago, so thought I'd use it again; however, I have been met with problems right from the start.

Firstly I was unable to compile as a non existent scss is imported.  I managed to work around that by not importing from angular-star-rating, but from css-star-rating instead.

Then I was unable to get value of rating component using methods provided in documentation.
I have tried all of them and none work for me, the imports are no longer valid and replacing them with the (I assume) new versions still doesn't work.

I have tried:
[(ngModel)]="selectedReview.rating",
(ngModel)="selectedReview.rating",
(onClick)="selectedReview.rating = $event.rating",
(onRatingChange)="selectedReview.rating = $event.rating"
(onClick)="onClick($event)"
(onclick)="onClick($event)"
(onRatingChange)="onRatingChange($event)"
(click)="onClick($event)" <= the only time an event was fired, sadly a mouse event though.

I also tried setting up ViewChild / elementRef, but as it isn't an element got no where.
My markup is:
                <star-rating-comp [starType]="'svg'"
                                  id="newRating"
                                  name="newRating"
                                  [rating]="selectedReview.rating || 5"
                                  [hoverEnabled]="true"
                                  (onClick)="selectedReview.rating = $event.rating">
                </star-rating-comp>
## Expected behavior

value of rating added to / update the object property "selectedReview.rating" which is of type number.
scss to be properly imported

## Minimal reproduction of the problem with instructions

followed documentation.

## Environment
Using Angular Universal for SSR on Asp.net Core 2.0
<pre><code>
Library version:@latest
Angular version: 5.2.9

Browser:

- [ ] Chrome (desktop) Version 65.0.3325.181 (Official Build) (64-bit)
</code></pre>

**Comment by BioPhoton** [comment]
I guess this related to #86 

I updated the documentation as the event binding names changed.

Feel free to reopen the issue if need.
