### ISSUE TITLE
~/css-star-rating/dist/scss/star-ratings.scss couldn't be resolved

### ISSUE THREAD

**Issue by juleskreutzer** [BioPhoton/angular-star-rating#85]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior
Module build failed: Error: Can't resolve 'css-star-rating/dist/scss/star-rating.scss' in ...

## Expected behavior
I expect that the file can be resolved

## Minimal reproduction of the problem with instructions
Install version 3.0.8 and set it up. It can't find the file ~/css-star-rating/dist/scss/star-rating.scss because the path is invalid. I think it could be solved by pointing to the folder ~/css-star-rating/scss/star-rating.scss

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 5

</code></pre>

**Comment by maelfosso** [comment]
@juleskreutzer I also had the same problem

1. Open `node_modules/angular-star-rating/assets/scss/star-rating.scss`
2. Change `~css-star-rating/dist/scss/star-rating.scss` with `"~css-star-rating/scss/star-rating.scss";`
3. You could see that by opening `node_modules/css-star-rating`. It doesn't have a folder `dist`

**Comment by BioPhoton** [comment]
Hi @juleskreutzer thx for this issue! :-)

This is should be fixed in the latest version.

Feel free to reopen this issue if needed.

**Comment by juleskreutzer** [comment]
Which is 4.0.0-beta3? Because I have this issue on 3.0.8

**Comment by BioPhoton** [comment]
Yes 4.0.0-beta.3

**Comment by BioPhoton** [comment]
I changed the selector btw... just that you know.

**Comment by juleskreutzer** [comment]
Great! I’ll give it a try when I have the time for it.
