### ISSUE TITLE
angular-star-rating has no exported member 'OnClickEvent'

### ISSUE THREAD

**Issue by TheZoker** [BioPhoton/angular-star-rating#86]
In [this](https://github.com/BioPhoton/angular-star-rating/wiki/Implement-event-bindings) wiki article you write, that we should use:
```
import {OnClickEvent, OnRatingChangeEven, OnHoverRatingChangeEvent} from "angular-star-rating";
```

But with version 4.0.0-beta2 I get this issue:

angular-star-rating has no exported member 'OnClickEvent', 'OnRatingChangeEven', 'OnHoverRatingChangeEvent'

How to fix it?

**Comment by BioPhoton** [comment]
The events are renamed in the latest version 
I updated the docs: [Event-bindings](https://github.com/BioPhoton/angular-star-rating/wiki/Event-bindings)
