### ISSUE TITLE
[color] doesn't set color of stars

### ISSUE THREAD

**Issue by savchukm** [BioPhoton/angular-star-rating#9]
I'd like to set color of my stars, but there are some troubles.

According to documentation:

> color - A static color for the stars

Trying to set any color(default, negative, middle, positive) like this, but nothing changed:
`<star-rating-comp [color]="'positive'"></star-rating-comp>`

**Expected result:**
Color of stars will be set and current value doesn't affect the color.

**Actual result:**
For 0 value - grey
For 1 value - red
For 2-3 value - yellow
For 4-5 value - green

For now, it seems to me color will be set  automatically regardless 'color' property

**Comment by BioPhoton** [comment]
Hy @savchukm!

I updated a lot of bindings in the latest version. But in your case it was a docs issue. It's actually [staticColor]. Not [color]. Sry for this...

Please let me know if it works for you.

**Comment by BioPhoton** [comment]
feel free to reopen it...

**Comment by rsjunior** [comment]
Still not working for middle color

**Comment by BioPhoton** [comment]
Sry i changed the name to "ok" a while ago and forgot to update this line in the docs... *blush*

You can check it here: https://github.com/BioPhoton/angular-star-rating/blob/master/src/star-rating-struct.ts#L2
and here: https://github.com/BioPhoton/css-star-rating/blob/master/src/scss/_variables.scss#L16

best, 
michael

**Comment by rsjunior** [comment]
hi michael!

tks, "ok" works

**Comment by rubyboy** [comment]
"ok" worked. Should probably update docs :)
Thanks heaps for this library!
