### ISSUE TITLE
star.rating.scss is missing 

### ISSUE THREAD

**Issue by VivekIshir** [BioPhoton/angular-star-rating#90]
HI i m seeing only one file inside the assets\images, document saying to import the "star-rating.scss"
Its looking star-rating.scss is missing ? Anybody please help,
i m using npm install angular-star-rating --save

![image](https://user-images.githubusercontent.com/34680272/39823936-bd17633c-53cb-11e8-8b48-7afa061eb97e.png)

**Comment by BioPhoton** [comment]
Did you try to install the latest version?

**Comment by VivekIshir** [comment]
What i need to install ? Does it  npm install angular-star-rating@3.0.8 --save

**Comment by BioPhoton** [comment]
Try `npm I angular-star-rating@4.0.0-beta.3`

**Comment by VivekIshir** [comment]
@BioPhoton still not seeing star-rating.scss" installed , i just run 'npm install angular-star-rating@4.0.0-beta.3'


![image](https://user-images.githubusercontent.com/34680272/39850805-fb36fe60-5430-11e8-802d-dc5ff4bcd212.png)

**Comment by VivekIshir** [comment]
@BioPhoton i m expecting 'star-rating.scss' should be there as per Document https://github.com/BioPhoton/angular-star-rating/wiki/Installing 

its asking for to import " @import "~angular-star-rating/assets/scss/star-rating" but in our installed package, it looking missing, Right ?
**look the Document line** -
**Import the star.rating.scss file i.e. import it in your styles.scss file with @import "~angular-star-rating/assets/scss/star-rating";**

b

**Comment by an-rahulpandey** [comment]
I also installed the latest version, but the scss folder is missing inside assets folder

**Comment by VivekIshir** [comment]
@an-rahulpandey @djfishe  https://www.npmjs.com/package/levon-angular-star-rating i used this one, Working well, CSS issue is fixed.

**Comment by BioPhoton** [comment]
Hi @VivekIshir !

I realized the readme was wrong. 

You have to import from `@import '~css-star-rating/scss/star-rating';` this is now in your peer dependencies. If you miss it in you npde_modules just install them `npm i css-star-rating --save-dev`

**Comment by BioPhoton** [comment]
Readme is also updated now.

**Comment by BioPhoton** [comment]
If there are still problems please reopen this issue!

**Comment by VivekIshir** [comment]
@BioPhoton Thanks for support, Its working now, could you please update the Document for installation, Will be a great help to others, Thanks Mate!!

**Comment by BioPhoton** [comment]
Should be done already:

https://github.com/BioPhoton/angular-star-rating/wiki/Installing

If not pls point me in the right direction

**Comment by github-sadegh** [comment]
hi . i have this error:

`@extend .star.direction-rtl;`

angular: 9
angular-star-rating version : "^4.0.0-beta.3"
.

**Comment by github-sadegh** [comment]
@BioPhoton
