### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by eyalhakim** [BioPhoton/angular-star-rating#92]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
</code></pre>

## Current behavior

angular-star-rating@4.0.0-beta.3 requires a peer of @angular/core@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of @angular/forms@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-star-rating@4.0.0-beta.3 requires a peer of css-star-rating@^1.2.4 but none is installed. You must install peer dependencies yourself.

## Expected behavior

Should upgrade project to Angular 6

## Environment

<pre><code>
Library version: X.Y.Z
Angular version: X.Y.Z

Browser:

- [ ] Chrome (desktop) version XX
</code></pre>

**Comment by kblestarge** [comment]
Is it impossible to use this library as is with Angular v6?

**Comment by eyalhakim** [comment]
It works

**Comment by kblestarge** [comment]
@eyalhakim how did you get it to work? And if it works then why did you create this issue?

When I follow the steps to upgrading my application to Angular v6 using `ng update @angular/core` I see this:

`Package "angular-star-rating" has an incompatible peer dependency to "@angular/forms" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.0.3").`

**Comment by eyalhakim** [comment]
remove angular-star-rating package, update angular, and re-install it. There will still be a warning which is why i created the issue but it works.

**Comment by kblestarge** [comment]
Hm, ok. I'll give that a shot. Thank you!

**Comment by vinayakpatil** [comment]
+1

**Comment by emannuell** [comment]
"@angular/cli": "~6.0.3",

Error:
`./src/styles.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./src/styles.css)
Module build failed: Error: Can't resolve 'css-star-rating/scss/star-rating' in `

"angular-star-rating": "^4.0.0-beta.3",

**Comment by vinayakpatil** [comment]
@BioPhoton Any updates on this one? Is 4.x release planned in near future to fix this?

```
warning " > angular-star-rating@3.0.8" has incorrect peer dependency "@angular/core@^4.0.0".
warning " > angular-star-rating@3.0.8" has incorrect peer dependency "@angular/forms@^4.0.0".
warning " > angular-star-rating@3.0.8" has incorrect peer dependency "rxjs@^5.1.0".
```

**Comment by BioPhoton** [comment]
Close as obsolete
