### ISSUE TITLE
Angular Star Rating Not Working: Ng -v = 5.2 ! Template Parse Errors

### ISSUE THREAD

**Issue by seyidaniels** [BioPhoton/angular-star-rating#93]
I have impoorted the StarRatingModule in my app module and  included StarRatingModule.forRoot() in the imports under app.module.

However, when i follow the guide and put the following tag in my app.component.html it gave 

 <star-rating-comp [starType]="'icon'"></star-rating-comp>

It is giving the following errror:

**_VM226234 compiler.js:707 Uncaught Error: Template parse errors:
Can't bind to 'starType' since it isn't a known property of 'star-rating-comp'.
1. If 'star-rating-comp' is an Angular component and it has 'starType' input, then verify that it is part of this module._**

**Comment by jedgrant** [comment]
@seyidaniels I got the same errors until I saved my app.module.ts file. After that, it worked fine. You have found that out already.

**Comment by tapas4java** [comment]
@seyidaniels `<star-rating-comp>` has been changed to `<star-rating>` it seems. Give it a try.
