### ISSUE TITLE
getting these stars when using the package in angular 6

### ISSUE THREAD

**Issue by hjjobs** [BioPhoton/angular-star-rating#94]
<img width="558" alt="screen shot 2018-07-07 at 4 03 49 pm" src="https://user-images.githubusercontent.com/13882879/42410084-e20b2188-8201-11e8-93a2-63dffc60118a.png">

Does anyone know a solution for this ?

**Comment by hjjobs** [comment]
@mischah @BioPhoton @sergkr  please help me with this.

**Comment by BioPhoton** [comment]
Find a minimal setup as stackblitz and all different usecases in the readme

https://github.com/BioPhoton/angular-star-rating/blob/master/README.MD

I'll close this as it is no issue.

**Comment by hjjobs** [comment]
unable to import scss file. can you help me with this i went through the readme still not able to figure out,..
