### ISSUE TITLE
Stars Disappear on Heroku

### ISSUE THREAD

**Issue by universesurfer** [BioPhoton/angular-star-rating#96]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
</code></pre>

## Current behavior
I successfully implemented the package in my application, however when I deployed to Heroku the stars disappeared on every page.  The element is still there, but the stars are invisible.

I am using v3.0.8 of angular-star-rating and Angular 5.

## Expected behavior
Stars would show as they do when running in localhost.

## Environment

<pre><code>
Library version: 3.0.8
Angular version: 5

Browser:

- [x] Chrome (desktop) version 67
-[x] Opera (desktop) version 54
-[x] Safari
-[x] Firefox
</code></pre>

Any suggestions much appreciated.  Thank you...

**Comment by BioPhoton** [comment]
Do you have any http errors when fetching the svg's?

**Comment by universesurfer** [comment]
Thanks for your response.  I receive no http errors, strangely.

If I inspect the element, and click where the stars should appear, the values will change.  It is still recording the star rating.

But they remain invisible.

**Comment by BioPhoton** [comment]
can you access the svg directly on the server?

**Comment by universesurfer** [comment]
Could this have something to do with the W3 xlink tags in the svg element?

When I remove them from the element, the same issue suddenly occurs but in my localhost.

Trying to determine why the links might be an issue while hosted on Heroku.

**Comment by universesurfer** [comment]
Well, I tried reconfiguring node to serve svg in multiple attempts, but it didn't work.  I did the simple, but elegant solution of simply switching to the icon type that you provide in your package, and it works.  Grateful you provided that alternative.  :-)
