### ISSUE TITLE
How can disable editing the existing rating 

### ISSUE THREAD

**Issue by nadeemkhoury** [BioPhoton/angular-star-rating#98]
Hi, 
I'm trying to use the component as View Only Rating. How can I customize the component not to be editable. Just to bind to existing value and not modified later. 
I tried this
`<star-rating [starType]="'svg'" disabled [rating]=2.3 ></star-rating>`
but it doesn't work. 

Thank you

**Comment by jaco-terbraak** [comment]
[readonly]="true"

**Comment by gazdagandras** [comment]
[readOnly]="true" was the proper option for me, using camelCase.
